version: "3.8"

services:
  goapp:
    build: .
    container_name: rest_jwt_goapp
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - pgsql
    command: air run main.go
    networks:
      - rest-go-jwt

  pgsql:
    image: postgres:alpine
    container_name: pgsql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - rest-go-jwt

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: always
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    depends_on:
      - pgsql
    networks:
      - rest-go-jwt

volumes:
  postgres-db:
  cloudbeaver:

networks:
  rest-go-jwt:
    driver: bridge
